/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./src/components/Home.vue')['default']
    MyTcg: typeof import('./src/components/MyTcg.vue')['default']
    NewsFeed: typeof import('./src/components/NewsFeed.vue')['default']
    P4: typeof import('./src/components/P4.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Square: typeof import('./src/components/Square.vue')['default']
    Twitter: typeof import('./src/components/Twitter.vue')['default']
    WindowsFile: typeof import('./src/components/WindowsFile.vue')['default']
  }
}
